### ISSUE TITLE
Delete a release

### ISSUE THREAD

**Issue by galderz** [operator-framework/operator-courier#71]
If you make a mistake with a release, how do you delete it from quay.io? The courier should be able to handle deleting a release.

**Comment by kevinrizza** [comment]
@galderz Currently, Quay.io does not support deleting individual releases. The only way to unpublish a release is to delete an entire repository, which is not recommended. Since bundles contain the full history of all versions, simply pushing a new bundle is equivalent to "overriding" a previous release.

**Comment by csomh** [comment]
Deleting releases is indeed not supported by the GUI, but the API does have an [endpoint for that](https://github.com/operator-framework/go-appr/blob/master/appr.spec.yaml#L344). OMPS [already uses it]((https://github.com/release-engineering/operators-manifests-push-service#removing-released-operators-manifests)).

**Comment by kevinrizza** [comment]
@csomh

I want to be more clear here. Yes, technically the API backing the app-registry in Quay supports this delete mechanism. However, there are several issues with this:

1. App-Registry being the datastore for operators in quay is a short term solution to a long term problem. The current implementation was not designed for operators, and the API reflects that. Operator releases should not be deleted when they are published publically because they have upgrade logic and all previous versions baked into them. If one was published and then deleted and replaced with logic that did not work with that released operator, the upgrade path would break.

2. In the future, a first class datastore for operator storage will exist. When that happens the `operator-courier` will move to that new storage. While that API has yet to be fully be designed, my guess is that deleting releases may not generally be supported by a common consumable endpoint.

3.Implementing this now on courier will technically be possible, but it is not in the stated goals of courier (a publisher) and it may not be supported someday. Therefore I would prefer to avoid implementation for such a feature at this time.

If first class storage for operators is implemented with a Delete API for specific releases, then we could revisit this workflow in the future. As it is however, the correct workflow is to provide an upgrade path for a release in a subsequent release.

**Comment by galderz** [comment]
Ok, but what about if we make a mistake with a release? Say you push, via operator courier, operator version 1.2.3, but there's a problem with it (e.g. something wrong with a descriptor). There's no way to fix the issue and override the operator version 1.2.3. The only way is to up the quay.io version or something, e.g. version 1.2.4 in quay which adds operator version 1.2.3. I can see this getting quite confusing very quickly...

If delete is not possible, it should be possible to re-push a specific version. Last I checked there was an error when you pushed an existing version again.

**Comment by kevinrizza** [comment]
@galderz you shouldn't recreate a version. once that is published, someone will pick it up (probably through automatic updates). If there is something wrong with the version that is pushed, you should create a new version that includes an upgrade path to the fix. It is also possible to, through the csv, define versions to skip when going from older updates. But once it's in the wild, the operator owner needs to provide a path to upgrade, since the bundle should contain the whole history of every version.

If there is something genuinely seriously wrong with the bundle (like it contains an image reference that includes something that ruins the system it runs on) that should be an absolute worst case scenario and should be handled manually. The `operator-courier` shouldn't be part of resolving such a systemic failure.

**Comment by galderz** [comment]
Yeah, but the csv version is completely independent from the repository version on quay. I mean, I can have 10 versions on quay.io, each with different version, that refer to exactly operator version, but with/without descriptor changes. This doesn't make a lot of sense. Overriding or deleting a release should be doable. Without it I think it'll become a big mess.

**Comment by kevinrizza** [comment]
That doesn't change the fact that the minute the bundle is pushed to Quay it is available to the world. We do not want to be in a position that some user downloaded a bundle that is now impossible to upgrade from. It's not impossible to delete a release, it's just not a feature that the `operator-courier` should not be concerned with. Again, the `operator-courier` is not an implementation of the Quay API, it's just a means of using one of their apis. There is nothing stopping you from calling their delete API directly -- I am just strongly recommending against putting something like that into a normal workflow. It's just that that should always be a last resort manual intervention. Which is why `courier` should not implement such a command.

**Comment by kevinrizza** [comment]
Closing as out of scope of this project.
